# Generated by Django 2.2.7 on 2019-12-02 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('dbms', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL')], max_length=16)),
                ('admin_username', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_custom', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('static', 'Static'), ('php', 'PHP'), ('dynamic', 'Dynamic')], max_length=16)),
                ('purpose', models.CharField(choices=[('legacy', 'Legacy'), ('user', 'User'), ('project', 'Project'), ('activity', 'Activity'), ('other', 'Other')], max_length=16)),
                ('port', models.IntegerField(unique=True)),
                ('process_path', models.CharField(blank=True, max_length=100)),
                ('sites_domain_enabled', models.BooleanField(default=True)),
                ('database', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='sites.Database')),
                ('docker_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.DockerImage')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('create_site', 'Creating site'), ('rename_site', 'Renaming site'), ('change_site_type', 'Changing site type'), ('change_site_domains', 'Changing site domains'), ('regen_nginx_config', 'Regenerating Nginx configuration'), ('create_site_database', 'Creating site database'), ('delete_site_database', 'Deleting site database'), ('regen_database_password', 'Regenerating database password'), ('delete_site', 'Deleting site')], max_length=16)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='You can only have one sites.tjhsst.edu domain, and it must match the name of your site.', regex='^(?!(.*\\.)?sites\\.tjhsst\\.edu$)[0-9a-zA-Z_\\- .]+$')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=8)),
                ('creating_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='DockerImageExtraPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_packages', to='sites.DockerImage')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.DatabaseHost'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('started_time', models.DateTimeField(null=True)),
                ('before_state', models.CharField(blank=True, max_length=255)),
                ('after_state', models.CharField(blank=True, max_length=255)),
                ('equivalent_command', models.CharField(blank=True, max_length=200)),
                ('result', models.BooleanField(default=None, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Operation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dockerimageextrapackage',
            constraint=models.UniqueConstraint(fields=('image', 'name'), name='unique_image_package'),
        ),
    ]
