# Generated by Django 2.2.8 on 2019-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20191209_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
