# Generated by Django 2.2.8 on 2019-12-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_action_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='started_time',
            new_name='created_time',
        ),
    ]
