# Generated by Django 2.2.8 on 2019-12-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20191209_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='started_time',
            field=models.DateTimeField(null=True),
        ),
    ]
