# Generated by Django 2.2.8 on 2019-12-09 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_operation_started_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(regex='^[a-z]+(_[a-z]+)+$')]),
        ),
    ]
