# Generated by Django 2.2.8 on 2019-12-13 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20191209_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Site names must consist of lowercase letters, numbers, and dashes. Names cannot start with a number, and dashes must go between two non-dash characters.', regex='^[a-z][a-z0-9]*(-[a-z0-9]+)*$')]),
        ),
    ]
