# Generated by Django 2.2.8 on 2019-12-20 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20191213_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='port',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10001), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
