# Generated by Django 2.2.8 on 2020-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_auto_20191220_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('create_site', 'Creating site'), ('rename_site', 'Renaming site'), ('edit_site_names', 'Changing site name/domains'), ('change_site_type', 'Changing site type'), ('regen_nginx_config', 'Regenerating Nginx configuration'), ('create_site_database', 'Creating site database'), ('delete_site_database', 'Deleting site database'), ('regen_database_password', 'Regenerating database password'), ('delete_site', 'Deleting site')], max_length=16),
        ),
    ]
