# Generated by Django 2.2.8 on 2020-01-17 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_auto_20200115_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
