# Generated by Django 2.2.9 on 2020-01-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_auto_20200117_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='port',
        ),
    ]
