# Generated by Django 2.2.9 on 2020-02-03 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_auto_20200201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(regex='^[a-z]+(_[a-z]+)+$')]),
        ),
    ]
