# Generated by Django 2.2.10 on 2020-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_auto_20200206_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=16),
        ),
    ]
