# Generated by Django 2.2.10 on 2020-02-10 18:48

import director.apps.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_auto_20200210_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='install_command_prefix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(director.apps.sites.models._docker_image_get_default_image), to='sites.DockerImage'),
        ),
    ]
