# Generated by Django 2.2.10 on 2020-02-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_auto_20200211_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='run_script_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
