# Generated by Django 2.2.10 on 2020-02-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_dockerimage_run_script_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='process_path',
        ),
    ]
