# Generated by Django 2.2.10 on 2020-02-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0023_remove_site_process_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
