# Generated by Django 2.2.10 on 2020-02-16 03:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0026_auto_20200215_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteResourceLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpus', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('mem_limit', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Must be either 1) blank for the default limit or 2) a number followed by one of the suffixes KiB, MiB, or GiB (powers of 1024) or KB, MB, GB (powers of 1000).', regex='^(\\d+(\\s*[KMG]i?B)?)?$')])),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_limits', to='sites.Site')),
            ],
        ),
    ]
