# Generated by Django 2.2.10 on 2020-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0029_remove_site_sites_domain_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasehost',
            name='admin_hostname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='databasehost',
            name='admin_port',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
