# Generated by Django 2.2.10 on 2020-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0030_auto_20200219_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='base_install_command',
            field=models.TextField(blank=True, default=''),
        ),
    ]
