# Generated by Django 2.2.10 on 2020-03-06 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0032_auto_20200221_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Site names must consist of lowercase letters, numbers, and dashes. Dashes must go between two non-dash characters.', regex='^[a-z0-9]+(-[a-z0-9]+)*$')]),
        ),
    ]
