# Generated by Django 2.2.10 on 2020-03-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0035_siteresourcelimits_client_body_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimage',
            name='base_install_command',
            field=models.TextField(blank=True, default='', help_text="A command to run after the setup commands, but before custom packages are installed. This should be used to install basic dependencies specific to this image; for something broader (OS/language-specific), use a setup command instead. Be careful about syntax errors; everything is '&&'-ed together."),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='description',
            field=models.TextField(blank=True, default='', help_text="A general description of what is in the image, what it's useful for, etc. The user will see this when they select an image."),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='friendly_name',
            field=models.CharField(blank=True, default=None, help_text='Will be shown to the user.', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='install_command_prefix',
            field=models.TextField(blank=True, default='', help_text="This is run with '<cmd> <pkgs>' where <cmd> is this command and <pkgs> is a space-separated list of packages."),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='name',
            field=models.CharField(help_text='These should always be ":latest" or equivalent images. Weird things will happen if they aren\'t. Warning: You cannot edit this field once the image has been created. Allowing that would break a fundamental assumption of the image handling code.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='run_script_template',
            field=models.TextField(blank=True, default='', help_text="The user will have the option to copy this into their site's run.sh when they select a Docker image."),
        ),
    ]
