# Generated by Django 2.2.12 on 2020-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0037_auto_20200407_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
