# Generated by Django 2.2.12 on 2020-05-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0038_dockerimage_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('sites', models.ManyToManyField(related_name='pending_users', to='sites.Site')),
            ],
        ),
    ]
