# Generated by Django 2.2.12 on 2020-05-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0039_sitependinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='user_recoverable',
            field=models.BooleanField(default=False),
        ),
    ]
