# Generated by Django 2.2.12 on 2020-05-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0040_action_user_recoverable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='equivalent_command',
        ),
    ]
