# Generated by Django 2.2.13 on 2020-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0041_remove_action_equivalent_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Administrative comments. If availability != enabled, this will be shown to the user.'),
        ),
        migrations.AddField(
            model_name='site',
            name='availability',
            field=models.CharField(choices=[('enabled', 'Enabled (fully functional)'), ('not-served', 'Not served publicly'), ('disabled', 'Disabled (not served, only viewable/editable by admins)')], default='enabled', help_text='Controls availability of the site (whether it is served publicly and whether it is editable)', max_length=10),
        ),
    ]
