# Generated by Django 2.2.13 on 2020-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0042_auto_20200618_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='admin_comments',
            field=models.TextField(blank=True, help_text="Administrative comments. All users who have access to the site will always be able to see this, even if the site's 'availability' is 'disabled'."),
        ),
    ]
