# Generated by Django 2.2.13 on 2020-08-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0043_auto_20200618_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='custom_nginx_config',
            field=models.TextField(blank=True, help_text='Custom rules to add to the Nginx config (in the location /) block'),
        ),
    ]
