# Generated by Django 2.2.13 on 2020-09-16 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0044_site_custom_nginx_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid domain. (Note: You can only have one sites.tjhsst.edu domain, and it must match the name of your site.)', regex='^(?!(.*\\.)?sites\\.tjhsst\\.edu$)[a-z0-9]+(-[a-z0-9]+)*(\\.[a-z0-9]+(-[a-z0-9]+)*)+$$')]),
        ),
    ]
