# Generated by Django 2.2.17 on 2020-11-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0045_auto_20200915_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimage',
            name='name',
            field=models.CharField(help_text='These should always be ":latest" or equivalent images. Weird things will happen if they aren\'t. Warning: You cannot edit this field once the image has been created. Allowing that would break a fundamental assumption of the image handling code.', max_length=75, unique=True),
        ),
    ]
