# Generated by Django 2.2.10 on 2020-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterequest',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siterequest',
            name='private_admin_comments',
            field=models.TextField(blank=True),
        ),
    ]
