name: CI

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

.anchors:
  python_versions: &python_versions
    - 3.7

  python_setup: &python_setup
    name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}

  repo_setup: &repo_setup
    name: Set up repo
    uses: actions/checkout@v4

  setup_cache: &setup_cache
    name: Set up cache
    if: env.ACT != 'true'        # still skip cache in act runs
    uses: actions/cache@v4
    with:
      path: |
        ~/.cache/pip
        ~/.cache/pipenv
      key: ${{ matrix.python-version }}

  pin_pip: &pin_pip
    # Ensure pip is <24.1 so Celery 5.0.5 metadata is accepted
    name: Pin pip below 24.1 for Celery 5.0.5
    run: |
      python -m pip install "pip<24.1"
      python -m pip --version

  install_pipenv: &install_pipenv
    name: Install pipenv
    run: pip install pipenv

  install_manager_dependencies: &install_manager_dependencies
    name: Install manager dependencies
    working-directory: ./manager
    run: |
      if [ "${ACT:-false}" = "true" ]; then
        echo "Running under act – loosening pipenv constraints for manager"
        pipenv install --dev --skip-lock
      else
        pipenv install --dev --deploy
      fi

  install_orchestrator_dependencies: &install_orchestrator_dependencies
    name: Install orchestrator dependencies
    working-directory: ./orchestrator
    run: |
      if [ "${ACT:-false}" = "true" ]; then
        echo "Running under act – loosening pipenv constraints for orchestrator"
        pipenv install --dev --skip-lock
      else
        pipenv install --dev --deploy
      fi

  install_router_dependencies: &install_router_dependencies
    name: Install router dependencies
    working-directory: ./router
    run: |
      if [ "${ACT:-false}" = "true" ]; then
        echo "Running under act – loosening pipenv constraints for router"
        pipenv install --dev --skip-lock
      else
        pipenv install --dev --deploy
      fi

  install_shell_dependencies: &install_shell_dependencies
    name: Install shell dependencies
    working-directory: ./shell
    run: |
      if [ "${ACT:-false}" = "true" ]; then
        echo "Running under act – loosening pipenv constraints for shell"
        pipenv install --dev --skip-lock
      else
        pipenv install --dev --deploy
      fi

  generate_shell_keys: &generate_shell_keys
    name: generate shell signing keys
    working-directory: ./manager
    run: |
      sudo mkdir -p /etc/director-shell-keys/etc/ssh
      sudo chown -R $USER:$(id -gn) /etc/director-shell-keys
      pipenv run python ../scripts/generate-rsa-key.py 4096 /etc/director-shell-keys/shell-signing-token-pubkey.pem /etc/director-shell-keys/shell-signing-token-privkey.pem
      pipenv run python ../scripts/generate-rsa-key.py 4096 /etc/director-shell-keys/shell-encryption-token-pubkey.pem /etc/director-shell-keys/shell-encryption-token-privkey.pem
      ssh-keygen -A -f /etc/director-shell-keys


jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: *python_versions

    steps:
      - *repo_setup
      - *python_setup
      - *pin_pip

      # Optional: force PyPI when running under act
      - name: Force PyPI when running under act
        if: env.ACT == 'true'
        run: |
          echo "PIP_INDEX_URL=https://pypi.org/simple" >> $GITHUB_ENV
          echo "PIP_TRUSTED_HOST=pypi.org" >> $GITHUB_ENV

      - *setup_cache
      - *install_pipenv
      - *install_manager_dependencies
      - *install_orchestrator_dependencies
      - *install_router_dependencies
      - *install_shell_dependencies
      - *generate_shell_keys

      # Shared
      - name: Check shared formatting with format.sh
        run: cd manager && pipenv run ../shared/scripts/format.sh && cd ../shared && test -z "$(git status --porcelain=v1 .)"

      - name: check shared formatting with check.sh
        working-directory: ./manager
        run: pipenv run ../shared/scripts/check.sh

      # Manager
      - name: Check manager formatting with format.sh and static_templates_format.sh
        working-directory: ./manager
        run: pipenv run ./scripts/format.sh && pipenv run ./scripts/static_templates_format.sh && test -z "$(git status --porcelain=v1 .)"

      - name: Check manager formatting with check.sh
        working-directory: ./manager
        run: pipenv run ./scripts/check.sh

      # Orchestrator
      - name: Check orchestrator formatting with format.sh
        working-directory: ./orchestrator
        run: pipenv run ./scripts/format.sh && test -z "$(git status --porcelain=v1 .)"

      - name: Check orchestrator formatting with check.sh
        working-directory: ./orchestrator
        run: pipenv run ./scripts/check.sh

      # Router
      - name: Check router formatting with format.sh
        working-directory: ./router
        run: pipenv run ./scripts/format.sh && test -z "$(git status --porcelain=v1 .)"

      - name: Check router formatting with check.sh
        working-directory: ./router
        run: pipenv run ./scripts/check.sh

      # Shell
      - name: Check shell formatting with format.sh
        working-directory: ./shell
        run: pipenv run ./scripts/format.sh && test -z "$(git status --porcelain=v1 .)"

      - name: Check shell formatting with check.sh
        working-directory: ./shell
        run: pipenv run ./scripts/check.sh
  

  test:
    # If you want 20.04 specifically, change this to ubuntu-20.04
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: *python_versions
      
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379          # keep original port mapping
        options: --entrypoint redis-server

    steps:
      - *repo_setup
      - *python_setup
      - *pin_pip

      - name: Force PyPI when running under act
        if: env.ACT == 'true'
        run: |
          echo "PIP_INDEX_URL=https://pypi.org/simple" >> $GITHUB_ENV
          echo "PIP_TRUSTED_HOST=pypi.org" >> $GITHUB_ENV

      - *setup_cache
      - *install_pipenv
      - *install_manager_dependencies
      - *install_orchestrator_dependencies
      - *install_router_dependencies
      - *install_shell_dependencies
      - *generate_shell_keys

      - name: install Kerberos
        run: sudo apt install -y krb5-user

      - name: copy manager secret.py
        working-directory: ./manager
        run: cp director/settings/secret.sample director/settings/secret.py

      # Manager
      - name: run Manager test suite
        working-directory: ./manager
        run: pipenv run coverage run manage.py test

      # Orchestrator
      - name: run Orchestrator test suite
        working-directory: ./orchestrator
        run: pipenv run coverage run -m unittest discover

      # Router
      - name: run Router test suite
        working-directory: ./router
        run: pipenv run coverage run -m unittest discover

      # Shell
      - name: run Shell test suite
        working-directory: ./shell
        run: |
          cp shell/settings/secret_dev.py shell/settings/secret.py
          pipenv run coverage run -m unittest discover
          pipenv run coverage combine
    
      - name: Combine coverage reports
        run: | 
          pip3 install coverage
          coverage combine manager/.coverage orchestrator/.coverage router/.coverage shell/.coverage

      - name: Report combined coverage report to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          pip3 install coveralls
          coveralls --service=github

  finish_success:
    needs:
      - lint
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Tell Coveralls that parallel jobs have finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
