# Generated by Django 2.2.12 on 2020-04-07 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_massemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemail',
            name='limit_users',
            field=models.ManyToManyField(blank=True, help_text='If this is empty, the email will be sent to ALL users!', related_name='_massemail_limit_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
