# Generated by Django 4.2.14 on 2024-07-09 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_graduation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massemail",
            name="limit_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="If this is empty, the email will be sent to ALL users!",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
